#! /bin/bash
clear
FLAG=1
while [ $FLAG = 1 ]
do
	echo "Please select an option:"
	echo
	echo "1) Display your current directory."
	echo "2) Display your home directory."
	echo "3) List the contents of the current directory."
	echo "4) Exit the script."
	echo
	read CHOICE
	if [ $CHOICE = 1 ]
		then
		pwd
	else
		if [ $CHOICE = 2 ]
			then
			echo $HOME
		else
			if [ $CHOICE = 3 ]
				then
				ls
                        else
				if [ $CHOICE = 4 ]
					then
					exit 0
			
				else
					echo "Invalid option."
				fi
			fi
		fi
	fi
done
echo "Finishing script..."
